### ISSUE TITLE
can we move this to RedhatQE

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mfalesni/lint-rebase-bugger#2]
hi it seems we missed this one

can we get it moved to the org repo?

**Comment by mfalesni** [comment]
@RonnyPfannschmidt oh, I did not notice this one. Yes, you can. Someone with rights in RedhatQE should just fork it in there and fix the repo references on the vm that does the bugging.

**Comment by RonnyPfannschmidt** [comment]
@mfalesni i was wondering about just moving the repo over to the org, unless you need/want to keep yours of course

**Comment by mfalesni** [comment]
@RonnyPfannschmidt I have no use for it, so it can be moved. Can I initiate it or you guys will do? I will hceck on my side now.

**Comment by mfalesni** [comment]
@RonnyPfannschmidt tell me to whom should I give admin access on this repo so he can then transfer it to RHQE org.

**Comment by RonnyPfannschmidt** [comment]
i shot it up on the CFME chat, well see when they wake and get into office

**Comment by mfalesni** [comment]
@RonnyPfannschmidt good :+1:

**Comment by smallamp** [comment]
@mfalesni I am one of the owners.. Pls give me the admin access on this repo.

**Comment by mfalesni** [comment]
@smallamp Hi Sudhir. I did initiate an ownership transfer. Feel free to accept and move.

**Comment by mshriver** [comment]
@mfalesni @smallamp I'm an admin on RedhatQE as well, @mfalesni I don't see any ownership transfer request though, can we re-try for this?

Thanks so much for working with us on this!

**Comment by mfalesni** [comment]
@mshriver Hey Mike, it seems like I missed your message. I initiated the transfer to you. Or if this lint bugger is no longer used, I might as well nuke it from the orbit.

**Comment by mshriver** [comment]
@mfalesni thanks so much, got the transfer to my namespace.  You can nuke your fork after that completes and we'll shepherd it from there.

**Comment by mfalesni** [comment]
It got transferred verbatim, so nothing else necessary to be done from my side. Thanks.

**Comment by RonnyPfannschmidt** [comment]
@mshriver ping, it seems the final transfer to the org was missed last year

**Comment by mshriver** [comment]
Transferred!
